//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogOdev.Models.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int YorumId { get; set; }
        public string Yorum1 { get; set; }
        public int MakaleID { get; set; }
        public Nullable<System.DateTime> YorumEklenmeTarihi { get; set; }
        public string YorumcuAdSoyad { get; set; }
        public Nullable<int> YorumBegeni { get; set; }
        public string YorumcuMail { get; set; }
        public string YorumcuWebAdresi { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
